name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-extras --dev --locked

      - name: Run Ruff Linter
        run: uv run ruff check --output-format=github .

      - name: Run Ruff Formatter
        run: uv run ruff format --check --output-format=github .

      - name: Run Mypy
        run: uv run mypy .

      - name: Run actionlint
        run: uv run actionlint

  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --locked
          uv pip install pytest-github-actions-annotate-failures

      - name: Run tests
        run: uv run pytest
